### ISSUE TITLE
Hover effect on doors

### ISSUE THREAD

**Issue by LorenzBischof** [puzzle/opensource-advent-challenge-2015#1]
I find the hover effect on the doors a bit jarring. Removing the underline might help. I would have created a pull request but I don't know where to change the css (there are multiple directories with scss, sass  and less)

**Comment by phil-pona** [comment]
Thanks for your Issue @lbischof, the same here, since @RolandStuder added the Jekyll Integration we have multiple CSS Precomilers.

Can you fix that @RolandStuder, ist probably the best way to stay on less since the basetemplate uses less as well.

**Comment by RolandStuder** [comment]
Ok, I removed the SASS files. And also I commented how to you Less in the readme. Closing this issue @lbischof you are welcome to change the hover state.

btw: I don't like how all the css is in one file. It is better to break things into components or modules and have one file per component. So if you add new stuff, consider isolating it in a seperate less-file.

**Comment by LorenzBischof** [comment]
Thanks. Removing the sass files seems to have resolved the issue.
