### ISSUE TITLE
Aktuellen Tag zugänglicher machen

### ISSUE THREAD

**Issue by RolandStuder** [puzzle/opensource-advent-challenge-2015#2]
Aktuell ist die Info hinter den Türchen versteckt, wollen wir das so? Denke es wäre gut, wenn man schon auf derm Homepage sieht, was aktuell geht. Man könnte zum Beispiel einen Block machen, der direkt die Contributions vom aktuellen Tag zeigt. Was meint ihr?

**Comment by LorenzBischof** [comment]
Finde ich eine super Idee. Die Frage ist nur ob es dann unordentlich wird mit all den Links. Vielleicht kann man eh ein Styleguide für die Links erstellen dh anstatt einen vollen commit Link lieber etwas wie [commit] oder [user/project/commit]?

**Comment by phil-pona** [comment]
finde ich eine gute Idee, go for it ;-)

**Comment by RolandStuder** [comment]
Habe jetzt grundsätzlich eine neue Darstellungsart gewählt. Aktueller Tag wird grad angezeigt. Ist nicht super elegant, das Scrollingverhalten müsste man noch optimieren. Und auch wie der aktuelle Tag ausgewählt wird und das zeuggs vom modal ist noch nicht voll ausgebaut.

**Comment by phil-pona** [comment]
sieht cool aus ;-)
