### ISSUE TITLE
Jumps to wrong position when opening door

### ISSUE THREAD

**Issue by LorenzBischof** [puzzle/opensource-advent-challenge-2015#3]
Beim Klick auf eine Türe springt die Seite an eine völlig falsche Stelle. Das nervt extrem, wenn man mehrere Tage anschauen will.

**Comment by RolandStuder** [comment]
Agreed. Ist bisher eine quick and dirty Lösung, Updates sind willkommen.

**Comment by LorenzBischof** [comment]
Ich bin der Sache noch ein wenig nach gegangen. Es scheint als ob zu dem Zeitpunkt, an dem der Hash geändert wird, die contributions noch nicht da sind. Das heisst height ist  0.

**Comment by LorenzBischof** [comment]
Fixed with commit 6957e0e. Habe die Animationen deaktiviert.
